
style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/shiqinfeng1/goframe-ddd
options:
  commits:
    filters:
      Type:
        - feat
        - "âœ¨ feat"
        - fix
        - "ğŸ› fix"
        - "ğŸ fix"
        - perf
        - "âš¡ï¸ perf"
        - "ğŸˆ perf"
        - refactor
        - "â™»ï¸ refactor"
        - "ğŸ¦„ refactor"
  commit_groups:
    title_maps:
      feat: "âœ¨ Features"
      "âœ¨ feat": "âœ¨ Features"
      fix: "ğŸ› Bug Fixes"
      "ğŸ› fix": "ğŸ› Bug Fixes"
      "ğŸ fix": "ğŸ Bug Fixes"
      perf: "âš¡ï¸ Performance Improvements"
      "âš¡ï¸ perf": "âš¡ï¸ Performance Improvements"
      "ğŸˆ perf": "ğŸˆ Performance Improvements"
      refactor: "â™»ï¸ Code Refactoring"
      "ğŸ¦„ refactor": "ğŸ¦„ Code Refactoring"
      "â™»ï¸ refactor": "â™»ï¸ Code Refactoring"
  header:
    pattern: "^([\\wâœ¨ğŸ›ğŸâš¡ï¸ğŸˆâ™»ï¸ğŸ¦„]+)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
